[project]
authors = ["Gary Miguel <garymm@garymm.org>"]
channels = ["conda-forge"]
name = "gpu-puzzles"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numba-cuda = ">=0.8"
ipykernel = ">=6.29.5,<7"
cuda = ">=12.4,<12.6"     # newer seems incompatible with numba somehow

[pypi-dependencies]
chalk-diagrams = { git = "https://github.com/chalk-diagrams/chalk", branch = "srush-patch-1" }
chalk-planar = { git = "https://github.com/chalk-diagrams/planar" }
